### DISCUSSION TITLE
Kubernetes-Perses UI-Ingress-Subpath setup

### DISCUSSION THREAD

**Discussion by OctavianHome** [perses/perses#2134] [Q&A]
I installed Perses Helm Chart from here
https://github.com/perses/helm-charts
I need to expose perses UI via ingress as a subpath `/cluster-metrics` like this
https://cluster-dns.domain.com/cluster-metrics
I encountered two issues:
First issue is that the Perses main page is loading from this relative location: `src="/main.js"`
So I had to add an ingress annotations from `src="/main.js"`  into `src="/cluster-metrics/main.js"`  which apparently solves this issue.
The second issue is that the backend API (used by frontend UI) has the base URL set to `“/api/v1”` ( `api/v1/dashboards`).
Ideally it should be possible to be set to `"/cluster-metrics/main.js"`
I read Perses documentation but I couldn’t find how to setup this.
I tried to set and environment variable (chatgpt suggestion) for Perses pod
API_PREFIX=”/cluster-metrics"
But nothing worked.
Could you please help me to set the Perses API prefix so that the Perses UI to make requests against of `“/cluster-metrics/api/v1”` ?

**Comment by Nexucis** [comment]
Hello,

This is a known issue, for the moment there is no solution to prefix the API in Perses.
I guess we will need to work on it sooner than expected :)

**Reply by Nexucis** [reply]
I have opened a PR to fix these issues: https://github.com/perses/perses/pull/2135.

**Comment by Nexucis** [comment]
I'm closing this discussion as the PR has been merged. We are going to create a release soon. But if you don't want to wait, you can use the docker image built for the associated commit on the main branch

**Reply by OctavianHome** [reply]
Thanks @Nexucis for your fast support & guidance!
I will let you know my feedback.

**Reply by OctavianHome** [reply]
Hello @Nexucis 
I've used multiple image tags (`persesdev/perses:v0.47.0-rc0`, `v0.47-distroless-debug`, `latest`) with the following configuration file:

```
api_prefix: /metric-perses
security:
  readonly: false
  enable_auth: false
database:
  file:
    extension: json
    folder: /perses
 schemas:
  datasources_path: /etc/perses/schemas/datasources
  panels_path: /etc/perses/schemas/panels
  queries_path: /etc/perses/schemas/queries
  variables_path: /etc/perses/schemas/variables
provisioning:
  folders:
  - /etc/perses/datasources
  ```
But I've always got the same error:
`time="2024-08-02T09:18:26Z" level=warning msg="encryption_key is not provided and therefore it will use a default one. For production instance you should provide the key."
time="2024-08-02T09:18:26Z" level=fatal msg="unable to initialize the service manager: open /etc/perses/schemas/panels: no such file or directory"`

Do you know what I'm doing wrong?

**Reply by Nexucis** [reply]
You should update the schemas paths with the following config:

```yaml
schemas:
  panels_path: "/etc/perses/cue/schemas/panels"
  queries_path: "/etc/perses/cue/schemas/queries"
  datasources_path: "/etc/perses/cue/schemas/datasources"
  variables_path: "/etc/perses/cue/schemas/variables"
```

Note the `cue` folder in the new paths. That's because in the Dockerfile the paths where the schemas are stored changed: https://github.com/perses/perses/blob/main/Dockerfile#L14

We are working on something to simplify that so you don't need to know where the schemas should be stored
