### DISCUSSION TITLE
How to configure an external IdP?

### DISCUSSION THREAD

**Discussion by lucrus73** [perses/perses#2814] [Q&A] [answered]
The simple answer seems to be [here](https://perses.dev/perses/docs/auth/authentication/), except it doesn't tell where to save that [YAML snippet](https://perses.dev/perses/docs/auth/authentication/#configuration-example), and adding that at the and of my `config.yaml` yelds to Perses failing to start, complaining that:

`yaml: unmarshal errors: field authentication not found in type config.Config`

So, how do I configure Perses to make it authenticate users against an external OIDC Identity Provider? (It's Authentik in my case, but I assume that doesn't matter).

**Comment by Nexucis** [comment, marked as answer]
ah yeah it is missing the top config key `security` in the documentation.

```yaml
security:
  authentication:
    providers:
      # Enable or not the native Perses identity provider
      enable_native: true/false
      # Register one or several OIDC provider(s)
      oidc: []
      # Register one or several OAuth provider(s)
      oauth: []
```

-> https://perses.dev/perses/docs/configuration/configuration/#definition

I will modify the doc to add the top key

**Reply by lucrus73** [reply]
Thanks, now it starts. However external authentication does not work for me. Here is my security code snippet:

```
security:
  enable_auth: true
  authentication:
    providers:
      oidc:
      - slug_id: atg
        name: "ATG"
        client_id: "..."
        client_secret: "..."
        issuer: "https://sso-perses.example.com/application/o/perses/"
        redirect_uri: "https://perses.example.com/api/auth/providers/oidc/atg/callback"
```

After I login, in the browser I get:

`failed to exchange token: parsing of request failed: token contains an invalid number of segments`

I'm using [Authentik](https://goauthentik.io/) as external IdP.
