### ISSUE TITLE
Dashboard tags

### ISSUE THREAD

**Issue by AntoineThebaud** [perses/perses#1733]
### Proposal

We probably want the ability to tag dashboards, to enable another convenient way to search for the right one(s).

**Comment by ibakshay** [comment]
@Nexucis Thank you very much for the summarisation.
Let us maybe discuss this feature in the next weekly meeting and brainstorm further with others. 

@jgbernalp Would love to get your feedback, especially on the `perses-operator` side :)

**Comment by nicolastakashi** [comment]
I'm wondering if annotations would be a better place to store tags, usually annotations in Kubernetes are used to applications store informations in there and retrieve it later.

It would fit nice as a label if it was only one label, but since a dash can have as many labels as the user decide, I'd probably store under annotations with map of key value.

wdyt?

**Comment by dougkirkley** [comment]
I guess I could see something like that working.
I was looking up some examples and there are a few in the k8s docs around comma delimited lists.

https://kubernetes.io/docs/reference/labels-annotations-taints/#applyset-kubernetes-io-additional-namespaces

```
Kind: Dashboard
metadata:
  annotations:
    dashboard.perses.dev/tags: "oncall,high_severity"
```

**Comment by dougkirkley** [comment]
Also, I already had a PR merged into the operator side to enable adding annotations to the resources, so that should be supported already without any changes.

**Comment by jgbernalp** [comment]
I think adding a new `tags` field in the metadata will be beneficial for the UI, I think is great to be able to group dashboards in addition to the current hierarchical project structure. From the operator side, we are already doing some mapping between Perses metadata and k8s metadata, so it would be a good idea to follow @dougkirkley example with annotations. Nothing stops users from adding more labels or annotations in the CR, but we would have a clear place to store and sync between the intended tags for dashboards created in Perses. I think we should use `tags` instead of labels as labels can be used for other purposes specific to k8s, like reconciling a dashboard in a specific instance.

**Comment by nicolastakashi** [comment]
I'm wondering if UI couldn't read from annotations as well, I don't have a strong opinion on having tags as part of the spec, but it looks like metadata, so would be nice store on metadata and teach Ui leverage the metadata no?

**Comment by Nexucis** [comment]
On my side, I prefer to keep the UI stupid and simple with no parsing and convention.

But overall, it seems we are reaching a consensus: 

## In Perses core (perses/perses)

- Tags are in the metadata
- Tags are in a dedicated field named `tags` like 

```yaml
Kind: Dashboard
metadata:
  name: test
  tags:
  - oncall
  - high_severity
```

Since it's in the metadata, tags will be available for all Perses resources (datasource, project, roles etc.)

## In k8s Custom Resource (perses/perses-operator)

- Tags are in the annotations
- They are in a single value, separated by a comma and identified by a unique key `dashboard.perses.dev/tags` or perhaps just `perses.dev/tags`. Like that it's more generic and this thing can be applied for other resources like the datasource.

```yaml
kind: PersesDashboard
apiVersion: persesdashboards.perses.dev/v1alpha1
metadata:
  name: test
  namespace: monitoring
  annotations:
    perses.dev/tags : "oncall,high_severity"
```

Then the operator will implement the translation logic to have the tags in the corresponding field in Perses.

Anyone disagree ?
