### ISSUE TITLE
User that don't have access to Global<resource> shouldn't see the tab

### ISSUE THREAD

**Issue by Nexucis** [perses/perses#1844]
### What did you do?

I gave to default user a really strict access to global resources. In my config, the user doesn't have access to `GlobalRole` for example.

### What did you expect to see?

I shouldn't see the tab `Global Roles` if I can't read them

### What did you see instead? Under which circumstances?

I can see them and when I'm clicking on the tab, it doesn't display anything (as expected), but it doesn't even say there is a permission issue.

<img width="977" alt="image" src="https://github.com/perses/perses/assets/4548045/40614385-800d-42d4-9bc2-1adb0a012690">

### System information

Ubuntu last version

### Perses version

v0.44.0-rc2

### Perses configuration file

```yaml
security:
  readonly: false
  encryption_key: "=tW$56zytgB&3jN2E%7-+qrGZE?v6LCc"
  enable_auth: true
  authorization:
    guest_permissions:
      - actions:
          - read
        scopes:
          - GlobalDatasource
          - GlobalSecret
      - actions:
          - create
        scopes:
          - Project
  authentication:
    providers:
      enable_native: true

database:
  file:
    folder: "dev/local_db"
    extension: "json"
    case_sensitive: false

provisioning:
  folders:
  - "dev/data"

schemas:
  panels_path: "cue/schemas/panels"
  queries_path: "cue/schemas/queries"
  datasources_path: "cue/schemas/datasources"
  variables_path: "cue/schemas/variables"
  interval: "5m"

important_dashboards:
  - project: "perses"
    dashboard: "Demo"
  - project: "testing"
    dashboard: "DuplicatePanels"
  - project: "Unknown"
    dashboard: "Dashboard"

information: |-
  # Hello World
  ## File Database setup

ephemeral_dashboards_cleanup_interval: "1h"
```
