### ISSUE TITLE
CLI: Unable to create a project when no read permission are given by default

### ISSUE THREAD

**Issue by Nexucis** [perses/perses#1904]
### What did you do?

0. I'm using the Perses dev environment
1. Give default guest permission to be able to only create a project (so no read permission on anything)
2. login with the `guest` user

```bash
./bin/percli login --username=guest http://localhost:8080
```

3. Try to create a project using the CLI

```bash
project='{
  "kind": "Project",
  "metadata": {
    "name": "MyProject"
  }
}'
echo ${project} | ./bin/percli apply -f -
```

### What did you expect to see?

I expect I was able to create the project

### What did you see instead? Under which circumstances?

CLI returned the following error:

```bash
Error: unable to retrieve the "Project" from the Perses API. something wrong happened with the request to the API.  
Message: unauthorized: missing 'read' permission in 'myproject' project for 'Project' kind StatusCode: 401
```

Indeed I don't have the `read`permission for the project `myproject` since it doesn't exist yet (in this context). 

### System information

Darwin 23.4.0 arm64

### Perses version

v0.44.0

### Perses configuration file

```yaml
security:
  readonly: false
  encryption_key: "<secret>"
  enable_auth: true
  authorization:
    guest_permissions:
      - actions:
          - create
        scopes:
          - Project
  authentication:
    providers:
      enable_native: true
```
