### ISSUE TITLE
Authentication with Perses remote deployment not possible

### ISSUE THREAD

**Issue by GSX1400** [perses/perses#2066]
### What did you do?

Deploy Perses on a remote server, whether that be in AWS, DigitalOcean or any other provider and enabling authentication to get the login page results in an authentication loop/failure.

I have attempted this using both Docker and Binary install, as well as on various cloud platforms, with and without load balancer.

I have used Safari and Chrome to test with, with and without incognito.

The only way I can log into Perses is by using an SSH tunnel to the server hosting Perses.

More details and full discussion can be seen in the perses-dev channel on Matrix.

### What did you expect to see?

I expected to be logged into Perses

### What did you see instead? Under which circumstances?

Logging in will redirect back to the log-in page, as if nothing happened. 3 cookies are received, but then quickly erased, resulting in no authentication taking place.

### System information

Amazon Linux 2023, Ubuntu 24.04

### Perses version

0.45, 0.46 (but happens on older versions too)

### Perses configuration file

```yaml
database:
  file:
  folder: "./database"
  extension: "yaml"

schemas:
  panels_path: "./cue/schemas/panels"
  queries_path: "./cue/schemas/queries"
  datasources_path: "./cue/schemas/datasources"
  variables_path: "./cue/schemas/variables"
  interval: "6h"

security:

  # When it is true, the authentication and authorization config are considered.
  # And you will need a valid JWT token to contact most of the endpoints exposed by the API
  enable_auth: true

  authentication:
    disable_sign_up: false
    # Authentication providers
    providers:
      # List of the OIDC authentication providers
      enable_native: true
```

### Logs

```text
INFO[2024-06-12T10:05:27Z]  method=POST status=200 uri=/api/auth/providers/native/login
INFO[2024-06-12T10:05:27Z]  method=GET status=401 uri=/api/v1/projects
INFO[2024-06-12T10:05:27Z]  method=GET status=401 uri="/api/v1/dashboards?metadata_only=true"
INFO[2024-06-12T10:05:27Z]  method=GET status=200 uri=/api/config
INFO[2024-06-12T10:05:27Z]  method=GET status=401 uri=/api/v1/projects
INFO[2024-06-12T10:05:27Z]  method=POST status=400 uri=/api/auth/refresh
INFO[2024-06-12T10:05:27Z]  method=POST status=400 uri=/api/auth/refresh
INFO[2024-06-12T10:05:27Z]  method=POST status=400 uri=/api/auth/refresh
INFO[2024-06-12T10:05:27Z]  method=GET status=200 uri=/sign-in
INFO[2024-06-12T10:05:27Z]  method=GET status=200 uri=/sign-in
INFO[2024-06-12T10:05:27Z]  method=GET status=200 uri=/main.js
INFO[2024-06-12T10:05:29Z]  method=GET status=200 uri=/api/config
INFO[2024-06-12T10:05:29Z]  method=GET status=200 uri=/api/v1/health
INFO[2024-06-12T10:05:29Z]  method=GET status=500 uri=/8f28e0e1fdb195149f1c.woff2
INFO[2024-06-12T10:05:29Z]  method=GET status=500 uri=/be36596da218e1eec01c.woff2
INFO[2024-06-12T10:05:29Z]  method=GET status=500 uri=/3dc1eff492ab1f598560.woff
INFO[2024-06-12T10:05:29Z]  method=GET status=500 uri=/1e7707c9ec98d9b97e7f.woff
```

**Comment by celian-garcia** [comment]
Thanks for the issue. We're investigating. FYI, I just tested in Openshift, Azure Cloud, behind the Openshift router, and behind an Azure App Gateway and it works perfectly.

Interestingly in our side we don't have a refresh of the page. Whereas in a GIF you sent us in private, I noticed that there is a refresh and this is after/while the refresh that the cookies are flushed.

**Comment by celian-garcia** [comment]
Here is our config 
```yaml
    security:
      readonly: false
      enable_auth: true
      encryption_key_file: /etc/extra-secrets/encrypt/encryption.key

      authorization:
        guest_permissions:
        - actions:
          - read
          scopes:
          - "*"
        - actions:
          - create
          scopes:
          - Project

      
      authentication:
        providers:
          enable_native: true
          oidc:
          - <redacted>

    database:
      sql:
        addr: <redacted>
        allow_native_passwords: true
        db_name: perses
        net: tcp
        tls_config: <redacted>
      
    schemas:
      datasources_path: /etc/perses/cue/schemas/datasources
      interval: 5m
      panels_path: /etc/perses/cue/schemas/panels
      queries_path: /etc/perses/cue/schemas/queries
      variables_path: /etc/perses/cue/schemas/variables


    frontend:
      information: <redacted>

    provisioning:
      folders:
      - "/etc/perses/provisioning"
```

**Comment by Nexucis** [comment]
Could you provide what is the infrastructure you are using to deploy Perses ?

Like in DigitalOcean, do you deploy Perses on K8s ? With an ingress ? Or are you using an App platform ? 

I wanted to try on Digital ocean, but based on your input, I just have no idea what plan should I choose.

<img width="1223" alt="image" src="https://github.com/perses/perses/assets/4548045/a957173f-8884-49c2-9df7-29b047405bbf">

Please as much as possible, provide the necessary resources to be able to reproduce the issue as we are not able to reproduce it so far. Example of resources:
- helm chart files
- Load Balancer configuration
- DNS used
- Proxy configuration
- Any configuration files required to deploy the app in DigitalOcean / AWS

**Comment by GSX1400** [comment]
Guys, I appreciate the effort you are making towards a resolution, but I am not sure how exactly I can explain this as i've really not done much to the setup of Perses besides creating one user and enabling authentication (native)

I provided the configuration for Perses.

I am not sure what else you could need?

Initially I believed this was a load balancer issue. It's not.
Then I questioned whether it was an AWS-specific issue. It's not.

Again, my steps (in my case, I am using AWS, but I don't believe it matters):

1. Launch EC2 server with public IP
2. wget Perses release from Github onto server
3. Extract release
4. Apply config mentioned above and launch Perses
5. Create user
6. Attempt to log in

This results in failure to log in and cookies failing to be retained.

**Comment by blairmurray** [comment]
Hi All,

Just want to add my 2 cents also.

I have tried this also with docker and podman, then podman compose after seeing thats how the demo site was deployed and working with no issues.

I have deployed the following podman-compose.yaml and config.json and same as @GSX1400 it just has the same issue logging in.

Obviously the IP I used will need to be substituted for the public IP of the instance you are using.

`version: '3.8'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    security_opt:
      - label=type:container_runtime_t
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:z
      - ./acme.json:/acme.json:z
    ports:
      - "30080:80"
      - "30443:443"
      - "8080:8080"
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --providers.docker=true
    networks:
      - podman

  perses:
    image: persesdev/perses
    container_name: perses
    depends_on:
      - traefik
    ports:
      - "80:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.perses.rule=Host(`54.197.0.100`)"
      - "traefik.http.services.perses.loadbalancer.server.port=80"
    volumes:
      - ./config.yaml:/etc/perses/config.yaml:z
    networks:
      - podman

networks:
  podman:
    external: true`

`database:
  file:
    folder: "/perses"
    extension: "json"

schemas:
  panels_path: "/etc/perses/cue/schemas/panels"
  queries_path: "/etc/perses/cue/schemas/queries"
  datasources_path: "/etc/perses/cue/schemas/datasources"
  variables_path: "/etc/perses/cue/schemas/variables"
  interval: "6h"

security:

  # When it is true, the authentication and authorization config are considered.
  # And you will need a valid JWT token to contact most of the endpoints exposed by the API
  enable_auth: true
  readonly: false

  authorization:
    guest_permissions:
    - actions:
      - read
      scopes:
      - "*"
    - actions:
      - create
      scopes:
      - Project

  authentication:
    disable_sign_up: false
    # Authentication providers
    providers:
      # List of the OIDC authentication providers
      enable_native: true

provisioning:
      folders:
      - "/etc/perses/provisioning"`

**Comment by blairmurray** [comment]
Hi All,

Just want to add my 2 cents also.

I have tried this also with docker and podman, then podman compose after seeing thats how the demo site was deployed and working with no issues.

I have deployed the following podman-compose.yaml and config.json and same as @GSX1400 it just has the same issue logging in.

Obviously the IP I used will need to be substituted for the public IP of the instance you are using.

```
version: '3.8'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    security_opt:
      - label=type:container_runtime_t
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:z
      - ./acme.json:/acme.json:z
    ports:
      - "30080:80"
      - "30443:443"
      - "8080:8080"
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --providers.docker=true
    networks:
      - podman

  perses:
    image: persesdev/perses
    container_name: perses
    depends_on:
      - traefik
    ports:
      - "80:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.perses.rule=Host(`54.197.0.100`)"
      - "traefik.http.services.perses.loadbalancer.server.port=80"
    volumes:
      - ./config.yaml:/etc/perses/config.yaml:z
    networks:
      - podman

networks:
  podman:
    external: true
```

```
database:
  file:
    folder: "/perses"
    extension: "json"

schemas:
  panels_path: "/etc/perses/cue/schemas/panels"
  queries_path: "/etc/perses/cue/schemas/queries"
  datasources_path: "/etc/perses/cue/schemas/datasources"
  variables_path: "/etc/perses/cue/schemas/variables"
  interval: "6h"

security:

  # When it is true, the authentication and authorization config are considered.
  # And you will need a valid JWT token to contact most of the endpoints exposed by the API
  enable_auth: true
  readonly: false

  authorization:
    guest_permissions:
    - actions:
      - read
      scopes:
      - "*"
    - actions:
      - create
      scopes:
      - Project

  authentication:
    disable_sign_up: false
    # Authentication providers
    providers:
      # List of the OIDC authentication providers
      enable_native: true

provisioning:
      folders:
      - "/etc/perses/provisioning"
```
