### ISSUE TITLE
Chart Lines Blending Into One

### ISSUE THREAD

**Issue by rasmusvan** [perses/perses#2158]
### What did you do?

Used query `sum by (status_code) (
  label_replace(
    sum by (response_code) (
      increase(
        istio_requests_total{
          destination_workload_namespace=~'.*',
          destination_workload=~'${workloadName}',
          response_code!='0'
        }[4m]
      )
    ),
    'status_code', '${1}xx', 'response_code', '([0-9]).*'
  )
)
` to make a line chart on a panel

### What did you expect to see?

Separate lines for the different error codes as they are shown separately when hovering.

### What did you see instead? Under which circumstances?

2 different colors merge on a line at the peak of the chart line.
<img width="693" alt="image" src="https://github.com/user-attachments/assets/bb370b5c-2083-4184-aafe-eee483338628">
<img width="733" alt="image" src="https://github.com/user-attachments/assets/c38c0da3-1e7d-4bdc-9ebf-7916e6fddc06">

### System information

Darwin 23.5.0 arm64

### Perses version

0.42.1

### Perses configuration file

```yaml
{
  "kind": "Panel",
  "spec": {
    "display": {
      "name": "Network - status code"
    },
    "plugin": {
      "kind": "TimeSeriesChart",
      "spec": {
        "visual": {
          "stack": "all"
        }
      }
    },
    "queries": [
      {
        "kind": "TimeSeriesQuery",
        "spec": {
          "plugin": {
            "kind": "PrometheusTimeSeriesQuery",
            "spec": {
              "datasource": {
                "kind": "PrometheusDatasource",
                "name": "EntigoDatasource"
              },
              "query": "sum by (status_code) (\n  label_replace(\n    sum by (response_code) (\n      increase(\n        istio_requests_total{\n          destination_workload_namespace=~'.*',\n          destination_workload=~'${workloadName}',\n          response_code!='0'\n        }[4m]\n      )\n    ),\n    'status_code', '${1}xx', 'response_code', '([0-9]).*'\n  )\n)\n",
              "seriesNameFormat": "{{status_code}}"
            }
          }
        }
      }
    ]
  }
}
```
