### ISSUE TITLE
DataSource Proxy Causes Panic

### ISSUE THREAD

**Issue by kamijin-fanta** [perses/perses#2175]
### What did you do?

Set up a proxy for the Prometheus DataSource and used it in the explorer.

### What did you see instead? Under which circumstances?

A panic occurred.

### Perses configuration file

```yaml
{
  "kind": "GlobalDatasource",
  "metadata": {
    "name": "bbb",
    "createdAt": "2024-08-15T02:09:53.496403298Z",
    "updatedAt": "2024-08-15T02:09:53.496403298Z",
    "version": 0
  },
  "spec": {
    "default": false,
    "plugin": {
      "kind": "PrometheusDatasource",
      "spec": {
        "proxy": {
          "kind": "HTTPProxy",
          "spec": {
            "allowedEndpoints": [
              {
                "endpointPattern": "/api/v1/labels",
                "method": "POST"
              },
              {
                "endpointPattern": "/api/v1/series",
                "method": "POST"
              },
              {
                "endpointPattern": "/api/v1/metadata",
                "method": "GET"
              },
              {
                "endpointPattern": "/api/v1/query",
                "method": "POST"
              },
              {
                "endpointPattern": "/api/v1/query_range",
                "method": "POST"
              },
              {
                "endpointPattern": "/api/v1/label/([a-zA-Z0-9_-]+)/values",
                "method": "GET"
              }
            ],
            "secret": "aaa",
            "url": "https://localhost:1234/prometheus/api/v1/query_range"
          }
        }
      }
    }
  }
}
```

### Logs

```text
[PANIC RECOVER] runtime error: invalid memory address or nil pointer dereference goroutine 209 [running]:
github.com/perses/common/echo.(*Builder).build.Recover.RecoverWithConfig.func1.1.1()
	go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/recover.go:99 +0x165
panic({0x1c9aa60?, 0x33815a0?})
	go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/runtime/panic.go:770 +0x132
github.com/perses/perses/internal/api/impl/proxy.(*endpoint).proxyGlobalDatasource.func1({0xc000f2fc8b?, 0xc001779860?})
	ghq/github.com/perses/perses/internal/api/impl/proxy/proxy.go:151 +0x1b
github.com/perses/perses/internal/api/impl/proxy.newProxy({0x0, 0x0, {{0xc001812558, 0x14}, {0x1c78740, 0xc001779860}}}, {0xc000c16be2, 0xc}, {0x23d4c48, 0xc0002588d0}, ...)
	ghq/github.com/perses/perses/internal/api/impl/proxy/proxy.go:357 +0x153
github.com/perses/perses/internal/api/impl/proxy.(*endpoint).proxyGlobalDatasource(0xc0003ada40, {0x240ce10, 0xc001bb20a0}, {0x0, 0x0, {{0xc001812558, 0x14}, {0x1c78740, 0xc001779860}}})
	ghq/github.com/perses/perses/internal/api/impl/proxy/proxy.go:150 +0x13d
github.com/perses/perses/internal/api/impl/proxy.(*endpoint).proxySavedGlobalDatasource(0xc0003ada40, {0x240ce10, 0xc001bb20a0})
	ghq/github.com/perses/perses/internal/api/impl/proxy/proxy.go:185 +0x145
github.com/labstack/echo-jwt/v4.Config.ToMiddleware.func2.1({0x240ce10, 0xc001bb20a0})
	go/pkg/mod/github.com/labstack/echo-jwt/v4@v4.2.0/jwt.go:237 +0x3dd
github.com/labstack/echo/v4.(*Echo).add.func1({0x240ce10, 0xc001bb20a0})
	go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:587 +0x4b
github.com/perses/perses/internal/api/core.New.CheckProject.func3.1({0x240ce10, 0xc001bb20a0})
	ghq/github.com/perses/perses/internal/api/core/middleware/verification.go:93 +0x192
github.com/perses/perses/internal/api/core.New.HandleError.func2.1({0x240ce10?, 0xc001bb20a0?})
	ghq/github.com/perses/perses/internal/api/core/middleware/error.go:24 +0x22
github.com/perses/common/echo/middleware.(*Metrics).ProcessHTTPRequest-fm.(*Metrics).ProcessHTTPRequest.func1({0x240ce10, 0xc001bb20a0})
	go/pkg/mod/github.com/perses/common@v0.25.1/echo/middleware/metrics.go:72 +0x71
github.com/labstack/echo/v4/middleware.GzipWithConfig.func1.1({0x240ce10, 0xc001bb20a0})
	go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/compress.go:90 +0x26f
github.com/perses/common/echo.(*Builder).build.Logger.LoggerWithConfig.func2.1({0x240ce10, 0xc001bb20a0})
	go/pkg/mod/github.com/perses/common@v0.25.1/echo/middleware/logger.go:53 +0x68
github.com/perses/common/echo.(*Builder).build.Recover.RecoverWithConfig.func1.1({0x240ce10, 0xc001bb20a0})
	go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/recover.go:130 +0x114
github.com/labstack/echo/v4.(*Echo).ServeHTTP.func1({0x240ce10, 0xc001bb20a0})
	go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:668 +0x127
github.com/perses/common/echo.(*server).Initialize.RemoveTrailingSlash.RemoveTrailingSlashWithConfig.func1.1({0x240ce10, 0xc001bb20a0})
	go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/slash.go:117 +0x1fd
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000054fc8, {0x23dcbc0, 0xc00021c9a0}, 0xc0000fa000)
	go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:674 +0x327
net/http.serverHandler.ServeHTTP({0x23d4db0?}, {0x23dcbc0?, 0xc00021c9a0?}, 0x6?)
	go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc00116e3f0, {0x23eae98, 0xc0002862a0})
	go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 147
	go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/net/http/server.go:3290 +0x4b4

goroutine 1 [chan receive, 2 minutes]:
github.com/perses/common/async/taskhelper.JoinAll({0x23eaed0?, 0xc0004c2230?}, 0x6fc23ac00, {0xc0009b6100, 0x
```
