### ISSUE TITLE
Changing api_prefix Makes Perses UI Inaccessible

### ISSUE THREAD

**Issue by rasmusvan** [perses/perses#2179]
### What did you do?

In the docker image configuration I set the api_prefix field to "perses"

### What did you expect to see?

I expected to be able to access Perses on localhost:8080/perses

### What did you see instead? Under which circumstances?

localhost:8080 and localhost:8080/perses both give 404 error. 
The api requests do indeed now have the additional /perses in the url for example http://localhost:8080/perses/api/v1/globalrolebindings is a valid query that works as expected

### System information

Darwin 23.5.0 arm64

### Perses version

0.47.0

### Perses configuration file

```yaml
database:
  file:
    folder: "/perses"
    extension: "json"

schemas:
  panels_path: "/etc/perses/cue/schemas/panels"
  queries_path: "/etc/perses/cue/schemas/queries"
  datasources_path: "/etc/perses/cue/schemas/datasources"
  variables_path: "/etc/perses/cue/schemas/variables"
  interval: "6h"

api_prefix: "perses"

security:
  enable_auth: false
```

### Logs

```text
When going to http://localhost:8080/perses
2024-08-16 11:05:33 time="2024-08-16T08:05:33Z" level=info method=GET status=404 uri=/perses
2024-08-16 11:05:33 time="2024-08-16T08:05:33Z" level=debug method=GET status=404 uri=/favicon.ico
```
### Additional
https://matrix.to/#/!XNmgYIAndZOkEvQAbb:matrix.org/$vZ6V1vj3K2TkB2yuPAalq9sgOjEEuF93ttntnVYMItg?via=matrix.org&via=gitter.im
