### ISSUE TITLE
Rolebinding doesn't provisioning when has more then one external user

### ISSUE THREAD

**Issue by khimick** [perses/perses#2270]
### What did you do?

I've deployed perses in Kubernetes cluster. Perses is configured for user authentication from external ID provider (keycloak). 
I put perses  RBAC manifest files (roles, rolebindings) to provisioning directory and expect to load them to file database.

```yaml
kind: "GlobalRoleBinding"
metadata:
  name: admin
spec: 
  role: admin
  subjects:
    - kind: User
      name: admin
    - kind: User
      name: user1
```

### What did you expect to see?

I expect to load and apply rolebinding when **any** user from subject's list has logged in.

### What did you see instead? Under which circumstances?

A rolebining is loading only when the **first** user from subject's list has logged in. 

### Perses version

c9389926

### Logs
```yaml
security:
  readonly: false
  enable_auth: true
  encryption_key: encryption_key
  cookie:
    same_site: lax
    secure: false 
  authentication:
    disable_sign_up: true
    providers:
      enable_native: true
      oidc:
      - client_id: client_id
        client_secret: client_secret
        issuer: https://keycloak.example.com/realms/test
        name: CloudX
        redirect_uri: https://perses.example.com/api/auth/providers/oidc/keycloak/callback
        scopes:
        - openid
        - profile
        - email
        - groups
        - roles
        slug_id: keycloak 
  authorization:
    guest_permissions:
    - actions:
      - read
      scopes:
      - Project
      - Dashboard
      - Datasource
      - Secret 
database:
  file:
    extension: json
    folder: /perses
  
schemas:
  datasources_path: /etc/perses/cue/schemas/datasources
  interval: 5m
  panels_path: /etc/perses/cue/schemas/panels
  queries_path: /etc/perses/cue/schemas/queries
  variables_path: /etc/perses/cue/schemas/variables
provisioning:
  folders:
  - /etc/perses/provision
  interval: 1m
```
