### ISSUE TITLE
YAML Database Configuration Causes JSON Marshaling Errors

### ISSUE THREAD

**Issue by ibakshay** [perses/perses#2371]
### What did you do?

Configured the application with YAML database extension:

```yaml
  file:
    folder: "dev/local_db"
    extension: "yaml"
    case_sensitive: false
```    

Started the application
Accessed the web UI, which triggered API calls to /api/v1/projects and /api/v1/dashboards?metadata_only=true

### What did you expect to see?

- Successful API responses with status code 200
- Proper JSON responses from both endpoints
- Normal application functionality, similar to when using JSON extension

### What did you see instead? Under which circumstances?

Received 500 status code errors from multiple API endpoints
JSON marshaling errors in the logs:

For /api/v1/projects: 
```shell
error="json: error calling MarshalJSON for type json.RawMessage: invalid character 'k' looking for beginning of value"
```

```shell
For /api/v1/dashboards: error="json: error calling MarshalJSON for type json.RawMessage: invalid character ',' looking for beginning of value"
```

This only occurs when using yaml as the database.file.extension. The application works correctly when using json extension.

### System information

Apple M2 Pro

### Perses version

main latest

### Perses configuration file

```yaml
security:
  readonly: false
  encryption_key: "=tW$56zytgB&3jN2E%7-+qrGZE?v6LCc"
  enable_auth: true
  authorization:
    guest_permissions:
      - actions:
          - read
        scopes:
          - "*"
      - actions:
          - create
        scopes:
          - Project
  authentication:
    providers:
      enable_native: true

database:
  file:
    folder: "dev/local_db"
    extension: "yaml"
    case_sensitive: false

provisioning:
  folders:
    - "dev/data"

schemas:
  panels_path: "cue/schemas/panels"
  queries_path: "cue/schemas/queries"
  datasources_path: "cue/schemas/datasources"
  variables_path: "cue/schemas/variables"
  interval: "5m"

ephemeral_dashboard:
  enable: true
  cleanup_interval: 1h

frontend:
  explorer:
    enable: true

  important_dashboards:
    - project: "perses"
      dashboard: "Demo"
    - project: "perses"
      dashboard: "NodeExporter"
    - project: "perses"
      dashboard: "Benchmark"
    - project: "testing"
      dashboard: "Defaults"
    - project: "testing"
      dashboard: "StatChartPanel"
    - project: "testing"
      dashboard: "MarkdownPanel"

  information: |-
    # Hello World
    ## File Database setup
```

### Logs

```shell
For /api/v1/projects: 

error="json: error calling MarshalJSON for type json.RawMessage: invalid character 'k' looking for beginning of value"
```

```shell
For /api/v1/dashboards: error="json: error calling MarshalJSON for type json.RawMessage: invalid character ',' looking for beginning of value"
```
