### ISSUE TITLE
api_prefix - Not Applied to Fonts via Reverse Proxy

### ISSUE THREAD

**Issue by ibakshay** [perses/perses#2575]
### What did you do?

The api_prefix configuration in the Perses application works correctly for APIs but is not applied for fonts when the application is accessed via a reverse proxy. This results in 404 errors for font requests, as they are made without the api_prefix in the URL.

Steps to Reproduce:

1. Deploy the Perses application behind a reverse proxy (e.g., NGINX).
2. Configure the api_prefix in the Perses application.
3. Access the application through the reverse proxy in a browser.
4. Observe the network requests in the browser's developer tools.

### What did you expect to see?

All requests, including font requests, should include the configured `api_prefix` in their URLs, even when accessed via a reverse proxy.

### What did you see instead? Under which circumstances?

Font requests do not include the api_prefix, resulting in 404 errors. For example:

A font request is made to `http://localhost:9090/be36596da218e1eec01c.woff2` instead of `http://localhost:9090/<api_prefix>/be36596da218e1eec01c.woff2`.

#### Screenshot 1

<img width="1510" alt="Image" src="https://github.com/user-attachments/assets/9ec3daa2-9646-4bfb-b4dc-c0f3d5bc1ffb" />

#### Screenshot 2

<img width="1503" alt="Image" src="https://github.com/user-attachments/assets/51e1a5c3-f059-4bcd-9f75-b260a6d606c1" />

### Perses version

v0.50.0

### Perses configuration file

```yaml
api_prefix: /perses
security:
  readonly: false
  encryption_key: "=tW$56zytgB&3jN2E%7-+qrGZE?v6LCc"
  enable_auth: true
  authorization:
    guest_permissions:
      - actions:
          - read
        scopes:
          - "*"
      - actions:
          - create
        scopes:
          - Project
  authentication:
    providers:
      enable_native: true

database:
  file:
    folder: "dev/local_db"
    extension: "json"
    case_sensitive: false

provisioning:
  folders:
  - "dev/data"

schemas:
  panels_path: "cue/schemas/panels"
  queries_path: "cue/schemas/queries"
  datasources_path: "cue/schemas/datasources"
  variables_path: "cue/schemas/variables"
  interval: "5m"

ephemeral_dashboard:
  enable: true
  cleanup_interval: 1h

frontend:
  explorer:
    enable: true

  important_dashboards:
    - project: "perses"
      dashboard: "Demo"
    - project: "perses"
      dashboard: "NodeExporter"
    - project: "perses"
      dashboard: "Benchmark"
    - project: "testing"
      dashboard: "Defaults"
    - project: "testing"
      dashboard: "StatChartPanel"
    - project: "testing"
      dashboard: "MarkdownPanel"

  information: |-
    # Hello World
    ## File Database setup
```

### Logs

```text

```

**Comment by ibakshay** [comment]
@Nexucis, I tested the latest version `v0.50.1` behind the Kubernetes reverse proxy and am still facing a similar issue.
```shell
 kubectl proxy --port=8001
```

Now, the UI API calls are being made to:  
```
http://localhost:8001/<api_prefix>/be36596da218e1eec01c.woff2
```  
Instead of:  
```
http://localhost:8001/api/v1/namespaces/kube-monitoring/services/perses:8080/proxy/<api_prefix>/be36596da218e1eec01c.woff2
```

All backend API calls are working without any issues. For example, here is the API call made to fetch the projects:  
```yaml
Request URL:
http://localhost:8001/api/v1/namespaces/kube-monitoring/services/perses:8080/proxy/perses/api/v1/projects
Request Method:
GET
Status Code:
200 OK
Remote Address:
127.0.0.1:8001
Referrer Policy:
strict-origin-when-cross-origin
```

---

### Screenshot of the error:

![Image](https://github.com/user-attachments/assets/5dff6255-012a-4d39-973a-fac22f7c0628)

I also checked how Prometheus UI handles API calls when behind a reverse proxy, and here is a comparison screenshot:

![Image](https://github.com/user-attachments/assets/78ba7b61-f57a-43db-a3cd-a8383002bdff)

---

Let me know if you need any additional details.
