### ISSUE TITLE
Support Custom Lint Rules

### ISSUE THREAD

**Issue by nicolastakashi** [perses/perses#2646]
### Proposal

I propose extending the Perses Dashboard CLI with support for custom lint rules defined via a YAML configuration file that combines JSONPath and CEL. This approach would allow users to precisely target sections of their dashboard definitions and enforce tailored validations.

## Proposed Idea

Extend the Perses Dashboard CLI to support fully customizable lint rules by leveraging both JSONPath and CEL. This approach enables users to extract specific sections of a dashboard definition and apply precise validations to enforce organizational standards. The idea consists of two main components:

### Custom Rules Configuration:

| Field     | Type    | Description                                                               | Additional Notes                                       |
|-----------|---------|---------------------------------------------------------------------------|--------------------------------------------------------|
| name      | string  | Unique identifier for the lint rule.                                      | Required                                             |
| target    | string  | JSONPath expression to extract the relevant portion of the dashboard data.| Required; used to bind the extracted value as `value`  |
| assertion | string  | CEL expression that validates the extracted value.                      | Required; must evaluate to a boolean                 |
| message   | string  | Error message to display if the assertion fails.                        | Required                                             |
| enabled   | boolean | Flag indicating whether the rule is active.                             | Optional; defaults to `true` if omitted              |
| severity  | string  | Optional severity level for the rule (e.g., error, warning, info).         | Optional                                             |

#### Example

```yaml
version: "1.0"
rules:
  - name: "Dashboard Naming Convention"
    target: "$.metadata.name"
    assertion: "value.matches('^[a-z]+(-[a-z]+)*$')"
    message: "Dashboard name must be all lowercase letters with hyphens only."
    enabled: true
    severity: "error"

  - name: "At Least One Panel Exists"
    target: "$.panels"
    assertion: "value.size() > 0"
    message: "Dashboard must contain at least one panel."
    enabled: true
    severity: "error"
```

### Evaluation Pipeline 
   The CLI would process a dashboard file by:
   - Parsing the dashboard (whether in JSON or YAML) into a unified data structure.
   - Using the JSONPath expression from each rule to extract the target data.
   - Binding the extracted data to a variable (e.g., `value`) in a CEL environment.
   - Evaluating the CEL assertion against this value.
   - Reporting any rule violations along with their error messages and severity levels.

## Benefits

This enhancement directly empowers users by allowing them to tailor dashboard validations to their specific requirements. With the ability to precisely target parts of a dashboard using JSONPath and enforce complex conditions via CEL, users can ensure that every dashboard meets organizational standards—such as adhering to naming conventions or having all required elements. This customization reduces configuration errors, improves dashboard quality, and facilitates better collaboration by making validations part of the version-controlled configuration. Additionally, integrating these custom rules into GitOps workflows means that validations are automatically enforced during CI/CD processes, resulting in more reliable and predictable deployments.
