### ISSUE TITLE
Percli CLI error message is misleading

### ISSUE THREAD

**Issue by ibakshay** [perses/perses#2678]
### What did you do?

I want to use the `percli` tool to create a project. 

I successfully logged in. 
```yaml
╰─❯❯❯ percli login http://localhost:8080                                               
successfully logged in http://localhost:8080
```

### What did you see instead? Under which circumstances?

I want to apply a file to add a project
```yaml
percli apply -f ./project.json
```
I am getting the following error in the terminal. 

```
 ╰─❯❯❯ percli apply -f ./project.json                    
Error: unable to decode the response body. Error json: cannot unmarshal array into Go value of type v1.plain
```

Below is the logs from the perses pod. 
```
time="2025-02-24T15:44:00Z" level=info func="github.com/perses/common/echo.(*Builder).build.Logger.LoggerWithConfig.func2.1" file="/home/runner/go/pkg/mod/github.com/perses/common@v0.26.0/echo/middleware/logger.go:63" method=GET status=200 uri=/perses/api/v1/projects
```

Could you please tell me if it is a bug or am I missing something? 

Below is the project.json manifest file. 
```json
{
  "kind": "Project",
  "metadata": {
    "name": "test"
  },
  "spec": { "display": { "name": "test" } }
}
```

### System information

kubernetes

### Perses version

v0.50.1

### Perses configuration file

```yaml
api_prefix: /perses
security:
    readonly: false
    cookie:
        same_site: lax
        secure: false
    encryption_key: <secret>
    enable_auth: false
    authorization:
        check_latest_update_interval: 30s
    authentication:
        access_token_ttl: 15m
        refresh_token_ttl: 1d
        disable_sign_up: false
        providers:
            enable_native: false
database:
    file:
        folder: /perses
        extension: json
        case_sensitive: false
schemas:
    panels_path: /etc/perses/cue/schemas/panels
    queries_path: /etc/perses/cue/schemas/queries
    datasources_path: /etc/perses/cue/schemas/datasources
    variables_path: /etc/perses/cue/schemas/variables
    interval: 5m
provisioning:
    folders:
        - /etc/perses/provisioning
    interval: 10s
frontend:
    disable: false
    explorer:
        enable: false
    time_range:
        disable_custom: false
        options:
            - 5m
            - 15m
            - 30m
            - 1h
            - 6h
            - 12h
            - 1d
            - 1w
            - 2w
```

### Logs

```text
time="2025-02-24T15:44:00Z" level=info func="github.com/perses/common/echo.(*Builder).build.Logger.LoggerWithConfig.func2.1" file="/home/runner/go/pkg/mod/github.com/perses/common@v0.26.0/echo/middleware/logger.go:63" method=GET status=200 uri=/perses/api/v1/projects
```
