### ISSUE TITLE
Datasource autodiscovery not working as expected

### ISSUE THREAD

**Issue by ibakshay** [perses/perses#2711]
### What did you do?

1. Deploy Perses with the following datasource discovery configuration in ConfigMap:
```yaml
datasource:
  global:
    discovery:
      - name: "prometheus-k8s-discovery"
        kubernetes_sd:
          datasource_plugin_kind: "PrometheusDatasource"
          namespace: "kube-monitoring"
          service_configuration:
            enable: true
            port_name: "http-web"
            service_type: "ClusterIP"
          labels:
            app: prometheus-prometheus
```

2. Start the Perses pod.
3. Observe the pod logs, which show the fatal error preventing startup.

### What did you expect to see?

Perses should successfully register discovered Prometheus services as global datasources.
- The pod should start without fatal errors related to datasource discovery tasks.

### What did you see instead? Under which circumstances?

The pod fails to start and logs indicate that the task is not recognized as a valid SimpleTask or Task.
```
time="2025-03-05T16:01:17Z" level=fatal msg="unable to instantiate the tasks for datasource discovery: task is not a SimpleTask or a Task"
```

### System information

local kind cluster

### Perses version

persesdev/perses:main-2025-03-04-682a13f7-distroless-debug

### Perses configuration file

```yaml
api_prefix: /perses
    datasource:
      global:
        discovery:
          - name: "prometheus-k8s-discovery"
            kubernetes_sd:
              datasource_plugin_kind: "PrometheusDatasource"
              namespace: "kube-monitoring"
              service_configuration:
                enable: true
                port_name: "http-web"  # Matches the Prometheus service port name
                service_type: "ClusterIP"  # Fixed field name
              labels:
                app: prometheus-prometheus
    database:
      file:
        extension: json
        folder: /perses
    frontend:
      important_dashboards: ]
    provisioning:
      folders:
      - /etc/perses/provisioning
      interval: 1m
    schemas:
      datasources_path: /etc/perses/cue/schemas/datasources
      interval: 5m
      panels_path: /etc/perses/cue/schemas/panels
      queries_path: /etc/perses/cue/schemas/queries
      variables_path: /etc/perses/cue/schemas/variables
    security:
      cookie:
        same_site: lax
        secure: false
      enable_auth: false
      readonly: false
```

### Logs

```text
time="2025-03-05T16:01:17Z" level=fatal msg="unable to instantiate the tasks for datasource discovery: task is not a SimpleTask or a Task"
```

**Comment by ibakshay** [comment]
I am getting the below error from the perses pod now. 

```shell
perses time="2025-03-06T12:31:10Z" level=error msg="failed to execute kube discovery \"prometheus-k8s-discovery\": found '', expected: identifier after ','" func="github.com/perses/perses/internal/api/discovery/kubernetes.(*discovery).Execute" file="/home/runner/work/perses/perses/internal/api/discovery/kubernetes/kubernetes.go:101"
```

My Perses configuration for the service discovery as follows. 

```json
  "datasource": {
    "global": {
      "disable": false,
      "discovery": [
        {
          "name": "prometheus-k8s-discovery",
          "refresh_interval": "5m",
          "kubernetes_sd": {
            "datasource_plugin_kind": "PrometheusDatasource",
            "namespace": "kube-monitoring",
            "service_configuration": {
              "enable": true,
              "port_name": "http-web",
              "service_type": "ClusterIP"
            },
            "pod_configuration": {},
            "labels": {
              "app.kubernetes.io/name": "prometheus"
            }
          }
        }
      ]
    },
    "project": {
      "disable": false
    },
    "disable_local": false
  }
````

My prometheus service manifest is below. 

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: kube-monitoring
  labels:
    app: prometheus-prometheus
    app.kubernetes.io/managed-by: Helm
  name: prometheus-prometheus
  namespace: kube-monitoring
  resourceVersion: "188881"
spec:
  clusterIP: 10.96.34.114
  clusterIPs:
  - 10.96.34.114
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-web
    port: 9090
    protocol: TCP
    targetPort: 9090
  - appProtocol: http
    name: reloader-web
    port: 8080
    protocol: TCP
    targetPort: reloader-web
  - name: grpc
    port: 10901
    protocol: TCP
    targetPort: grpc
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

Am I missing something? @Nexucis

**Comment by Nexucis** [comment]
that's really cool you are testing this feature @ibakshay ! Thank you very much for your constant feedback !

I am currently adding tests on this specific part thanks to the input you gave. I think it's because of the label filter that is not well generated (like there is a comma at the end of the label selector generated by the Perses code)

**Comment by Nexucis** [comment]
@ibakshay does it work better if you remove the label selector in the discovery config ?

**Comment by ibakshay** [comment]
> [@ibakshay](https://github.com/ibakshay) does it work better if you remove the label selector in the discovery config ?

I have removed the label selector and tried. I am now getting the below error in the pod logs. 
```shell
perses time="2025-03-06T19:32:22Z" level=error msg="unable to create the globaldatasource \"kube-monitoring.prometheus-operated\"" func="github.com/perses/perses/internal/api/discovery/service.(*ApplyService).Apply" file="/home/runner/work/perses/perses/internal/api/discovery/service/service.go:45" error="bad request: invalid datasource kube-monitoring.prometheus-operated: spec: 2 errors in empty disjunction:\nspec.directUrl: field not allowed:\n    1:40\nspec.directUrl: invalid value \"\" (out of bound =~\"^https?://[^\\\\s/$.?#].[^\\\\s]*$\"):\n    ../etc/perses/plugins/prometheus/cue.mod/pkg/github.com/perses/perses/cue/schemas/common/url.cue:16:7\n    1:52\n    ../etc/perses/plugins/prometheus/schemas/datasource/prometheus.cue:28:13\n"
perses time="2025-03-06T19:32:22Z" level=error msg="unable to create the globaldatasource \"kube-monitoring.prometheus-prometheus\"" func="github.com/perses/perses/internal/api/discovery/service.(*ApplyService).Apply" file="/home/runner/work/perses/perses/internal/api/discovery/service/service.go:45" error="bad request: invalid datasource kube-monitoring.prometheus-prometheus: spec: 2 errors in empty disjunction:\nspec.directUrl: field not allowed:\n    1:40\nspec.directUrl: invalid value \"\" (out of bound =~\"^https?://[^\\\\s/$.?#].[^\\\\s]*$\"):\n    ../etc/perses/plugins/prometheus/cue.mod/pkg/github.com/perses/perses/cue/schemas/common/url.cue:16:7\n    1:52\n    ../etc/perses/plugins/prometheus/schemas/datasource/prometheus.cue:28:13\n"
```

My config looks like the following. 

```json
  "datasource": {
    "global": {
      "disable": false,
      "discovery": [
        {
          "name": "prometheus-k8s-discovery",
          "refresh_interval": "5m",
          "kubernetes_sd": {
            "datasource_plugin_kind": "PrometheusDatasource",
            "namespace": "kube-monitoring",
            "service_configuration": {
              "enable": true,
              "port_name": "http-web",
              "service_type": "ClusterIP"
            },
            "pod_configuration": {}
          }
        }
      ]
    },
    "project": {
      "disable": false
    },
    "disable_local": false
  }
```

**Comment by Nexucis** [comment]
awesome, thank you very much @ibakshay. I know what's going one I shall be able to provide an appropriate fix tomorrow.

**Comment by Nexucis** [comment]
I am reopening this issue as it is still not working.

**Comment by Nexucis** [comment]
@ibakshay PR #2723 is merged, let me know if you have more issues around the discovery!

**Comment by ibakshay** [comment]
> [@ibakshay](https://github.com/ibakshay) PR [#2723](https://github.com/perses/perses/pull/2723) is merged, let me know if you have more issues around the discovery!

It works now! Thanks a lot :) 
However, I have a question. So, I added a new prometheus instance. The perses did not detect this new prometheus service. I had to kill the pod and the perses is able to add the new prometheus instance as `GlobalDatasource` when it started again. 

Is it the expected behaviour? I thought the perses application will watch and will automatically add the new prometheus instance without having us to restart the pod. 🤔

**Comment by ibakshay** [comment]
Ii think we have to watch services with label selector instead of list services with label selector [here  in internal/api/discovery/kubernetes/service.go](https://github.com/ibakshay/perses/blob/main/internal/api/discovery/kubernetes/service.go#L39-L40). 

Watch services with label selector will look something like the below code snippet. 

```go
func (d *serviceDiscovery) discover(decodedSchema []*cuetils.Node) ([]*v1.GlobalDatasource, error) {
	// Create a watch for the Kubernetes services with the given label selector
	watcher, err := d.kubeClient.CoreV1().Services(d.namespace).Watch(context.Background(), metav1.ListOptions{
		LabelSelector: d.labelSelector,
	})
	if err != nil {
		return nil, err
	}
	defer watcher.Stop()

	var result []*v1.GlobalDatasource

	// Process events from the watch channel
	for event := range watcher.ResultChan() {
		service, ok := event.Object.(*corev1.Service)
		if !ok {
			logrus.Warn("Unexpected type received from service watcher")
			continue
		}

		// Check if the service type matches the configured type
		if len(d.cfg.ServiceType) != 0 && d.cfg.ServiceType != string(service.Spec.Type) {
			logrus.Tracef("service type %q doesn't match the configured service type %q", service.Spec.Type, d.cfg.ServiceType)
			continue
		}

		// Convert the service to a GlobalDatasource
		dts, convertErr := d.serviceToGlobalDatasource(*service, decodedSchema)
		if convertErr != nil {
			logrus.Error("Failed to convert service to GlobalDatasource:", convertErr)
			continue
		}
		if dts != nil {
			result = append(result, dts)
		}
	}

	return result, nil
}
```

**Comment by Nexucis** [comment]
so there is a refresh interval set by default to 5min. It will get the list of service every 5min.

But it can be lower like every 10s like in Prometheus

**Comment by Nexucis** [comment]
When I implemented the discovery, I was indeed thinking of using the watching possibility of k8s.
But for the same reason of Prometheus choose to frequently pool the k8s API, when supporting other discovery and you want to align the code (to have something a bit generic), watching does not really fit.

So that's the short reason we are pulling the data instead of watching them

**Comment by ibakshay** [comment]
> so there is a refresh interval set by default to 5min. It will get the list of service every 5min.
> 
> But it can be lower like every 10s like in Prometheus

Sounds great!. The refresh interval can be configured in `schemas.interval`, right? 
Adding a new prometheus instance works like a charm! 🚀


And maybe one last observation. Not critical. Looks like we are not removing the Prometheus instance from the `GlobalDatasources`  when the prometheus instance is removed from the cluster. 
I still see 2 prometheus instances in the UI even after I removed the second prometheus instance `prometheus-2` from the cluster.
Below is the error message in logs. I waited for ten mins ;)  

![Image](https://github.com/user-attachments/assets/c54d830b-7c59-462a-a5d8-cebba733e52b)

```shell
time="2025-03-07T11:35:54Z" level=error msg="error proxying, remote unreachable: target=http://prometheus-2-prometheus.kube-monitoring.svc:9090, err=dial tcp: lookup prometheus-2-prometheus.kube-monitoring.svc on 10.96.0.10:53: no such host" func="github.com/perses/perses/internal/api/impl/proxy.(*httpProxy).serve.func1" file="/home/runner/work/perses/perses/internal/api/impl/proxy/proxy.go:233" error="dial tcp: lookup prometheus-2-prometheus.kube-monitoring.svc on 10.96.0.10:53: no such host"
time="2025-03-07T11:36:54Z" level=error msg="error proxying, remote unreachable: target=http://prometheus-2-prometheus.kube-monitoring.svc:9090, err=dial tcp: lookup prometheus-2-prometheus.kube-monitoring.svc on 10.96.0.10:53: no such host" func="github.com/perses/perses/internal/api/impl/proxy.(*httpProxy).serve.func1" file="/home/runner/work/perses/perses/internal/api/impl/proxy/proxy.go:233" error="dial tcp: lookup prometheus-2-prometheus.kube-monitoring.svc on 10.96.0.10:53: no such host"

```

**Comment by Nexucis** [comment]
> Sounds great!. The refresh interval can be configured in schemas.interval, right?

It's in the discovery itself you can set this value. For example: 

```
discovery:
  global
    discovery:
    - name: "prometheus"
       refresh_interval: 10s
```

> And maybe one last observation. Not critical. Looks like we are not removing the Prometheus instance from the GlobalDatasources when the prometheus instance is removed from the cluster.

Yes this is definitely a miss in this feature. It's not yet implemented, because I wasn't sure how it can be deleted. One idea would be to have a way to identify the datasource created from the discovery, and then to compare what is stored in the database and what exists in the discovery.
