### ISSUE TITLE
In k8s, plugins location is not correct

### ISSUE THREAD

**Issue by ibakshay** [perses/perses#2718]
### What did you do?

I am not able to import any dashboards in the UI or create any dashboards using `provisioning` feature. 

### What did you expect to see?

- Dashboards get successfully provisioned using provisioning feature
- Dashboards can be imported successfully in the UI

### What did you see instead? Under which circumstances?

This is the error I see in the Perses App logs. 
```shell
perses time="2025-03-06T08:29:33Z" level=error msg="unable to create the \"Dashboard\" \"apiserver\"" func="github.com/perses/perses/internal/api/provisioning.(*provisioning).applyEntity" file="/home/runner/work/perses/perses/internal/api/provisioning/provisioning.go:96" error="bad request: schema not found for plugin PrometheusLabelValuesVariable"
perses time="2025-03-06T08:29:33Z" level=error msg="unable to create the \"Dashboard\" \"coredns\"" func="github.com/perses/perses/internal/api/provisioning.(*provisioning).applyEntity" file="/home/runner/work/perses/perses/internal/api/provisioning/provisioning.go:96" error="bad request: schema not found for plugin PrometheusLabelValuesVariable"
perses time="2025-03-06T08:29:33Z" level=error msg="unable to create the \"Dashboard\" \"kubernetes-container-resources\"" func="github.com/perses/perses/internal/api/provisioning.(*provisioning).applyEntity" file="/home/runner/work/perses/perses/internal/api/provisioning/provisioning.go:96" error="bad request: schema not found for plugin PrometheusLabelValuesVariable"
perses time="2025-03-06T08:29:33Z" level=error msg="unable to create the \"Dashboard\" \"kubernetes-node\"" func="github.com/perses/perses/internal/api/provisioning.(*provisioning).applyEntity" file="/home/runner/work/perses/perses/internal/api/provisioning/provisioning.go:96" error="bad request: schema not found for plugin PrometheusLabelValuesVariable"
perses time="2025-03-06T08:29:33Z" level=error msg="unable to create the \"Dashboard\" \"prometheus-details\"" func="github.com/perses/perses/internal/api/provisioning.(*provisioning).applyEntity" file="/home/runner/work/perses/perses/internal/api/provisioning/provisioning.go:96" error="bad request: schema not found for plugin PrometheusLabelValuesVariable"
```

Below is the screenshot when I try to import a dashboard. 

![Image](https://github.com/user-attachments/assets/82840b77-1562-4777-8b6c-55ad2102d1ec)

### System information

Local kind cluster

### Perses version

main-2025-03-05-e8a67a6c-distroless-debug

### Perses configuration file

```yaml
{
  "api_prefix": "/perses",
  "security": {
    "readonly": false,
    "cookie": {
      "same_site": "lax",
      "secure": false
    },
    "encryption_key": "<secret>",
    "enable_auth": false,
    "authorization": {
      "check_latest_update_interval": "30s"
    },
    "authentication": {
      "access_token_ttl": "15m",
      "refresh_token_ttl": "1d",
      "disable_sign_up": false,
      "providers": {
        "enable_native": false
      }
    }
  },
  "database": {
    "file": {
      "folder": "/perses",
      "extension": "json",
      "case_sensitive": false
    }
  },
  "schemas": {
    "panels_path": "/etc/perses/cue/schemas/panels",
    "queries_path": "/etc/perses/cue/schemas/queries",
    "datasources_path": "/etc/perses/cue/schemas/datasources",
    "variables_path": "/etc/perses/cue/schemas/variables",
    "interval": "5m"
  },
  "dashboard": {},
  "provisioning": {
    "folders": [
      "/etc/perses/provisioning"
    ],
    "interval": "10m"
  },
  "datasource": {
    "global": {
      "disable": false,
      "discovery": []
    },
    "project": {
      "disable": false
    },
    "disable_local": false
  },
  "variable": {
    "global": {
      "disable": false
    },
    "project": {
      "disable": false
    },
    "disable_local": false
  },
  "ephemeral_dashboard": {
    "enable": false,
    "cleanup_interval": "0s"
  },
  "frontend": {
    "disable": false,
    "explorer": {
      "enable": false
    },
    "time_range": {
      "disable_custom": false,
      "options": [
        "5m",
        "15m",
        "30m",
        "1h",
        "6h",
        "12h",
        "1d",
        "1w",
        "2w"
      ]
    }
  },
  "plugin": {
    "path": "plugins",
    "archive_path": "plugins-archive"
  }
}
```

### Logs

```text
perses time="2025-03-06T08:29:33Z" level=error msg="unable to create the \"Dashboard\" \"apiserver\"" func="github.com/perses/perses/internal/api/provisioning.(*provisioning).applyEntity" file="/home/runner/work/perses/perses/internal/api/provisioning/provisioning.go:96" error="bad request: schema not found for plugin PrometheusLabelValuesVariable"
perses time="2025-03-06T08:29:33Z" level=error msg="unable to create the \"Dashboard\" \"coredns\"" func="github.com/perses/perses/internal/api/provisioning.(*provisioning).applyEntity" file="/home/runner/work/perses/perses/internal/api/provisioning/provisioning.go:96" error="bad request: schema not found for plugin PrometheusLabelValuesVariable"
perses time="2025-03-06T08:29:33Z" level=error msg="unable to create the \"Dashboard\" \"kubernetes-container-resources\"" func="github.com/perses/perses/internal/api/provisioning.(*provisioning).applyEntity" file="/home/runner/work/perses/perses/internal/api/provisioning/provisioning.go:96" error="bad request: schema not found for plugin PrometheusLabelValuesVariable"
perses time="2025-03-06T08:29:33Z" level=error msg="unable to create the \"Dashboard\" \"kubernetes-node\"" func="github.com/perses/perses/internal/api/provisioning.(*provisioning).applyEntity" file="/home/runner/work/perses/perses/internal/api/provisioning/provisioning.go:96" error="bad request: schema not found for plugin PrometheusLabelValuesVariable"
perses time="2025-03-06T08:29:33Z" level=error msg="unable to create the \"Dashboard\" \"prometheus-details\"" func="github.com/perses/perses/internal/api/provisioning.(*provisioning).applyEntity" file="/home/runner/work/perses/perses/internal/api/provisioning/provisioning.go:96" error="bad request: schema not found for plugin PrometheusLabelValuesVariable"
```
