### ISSUE TITLE
Grafana dashboards migration reduce manual steps

### ISSUE THREAD

**Issue by DavidQuan-vmware** [perses/perses#2860]
### Proposal

Is it possible to enhance the migration tool to make the migration process smoother and reduce manual steps, such as modifying datasource name and changing metadata names.

**Comment by AntoineThebaud** [comment]
Could you detail how you imagine we could automate the filling of datasource name & adjusting metadata, as today we are expecting user inputs for these?

Btw if you have a mass migration to achieve, you should probably look at scripting something: I just saw we are lacking a proper documentation for the /migrate API, sorry for that, so putting the information there:
- if you are using Golang, you can rely on the client we provide https://github.com/perses/perses/blob/main/pkg/client/api/client.go#L29
- for anything else: the API endpoint is `/api/migrate`, POST call, and the expected body format is the following:
```json
{
    "grafanaDashboard": {
        # full grafana dashboard, JSON format
    }
}
```

**Comment by szuecs** [comment]
I don't know if I should open another issue but it somehow also fits here.

I don't understand the migration from grafana guide at all. https://perses.dev/perses/docs/migration/
Something I miss, but what?

## My steps

I have a super basic, empty config:

```
/perses# cat config.yaml
api_prefix: /api
security:
  encryption_key_file: ./secret.key
database:
  file:
    folder: "./data"
    extension: "json"
dashboard:
schemas:
provisioning:
datasource:
variable:
ephemeral_dashboards_cleanup_interval:
ephemeral_dashboard:
frontend:
plugin:
```

I started perses
```
perses --config config.yaml
..
⇨ http server started on 0.0.0.0:8080
```

steps to migrate:
```
percli login http://localhost:8080

# grafana dump dashboard to json
cat >grafana-dashboard.json
<paste grafana.json>

mkdir dashboards
percli migrate -f grafana-dashboard.json --online -o json > dashboards/perses-dashboard.json
percli apply -f dashboards/perses-dashboard.json
-> INFO[2025-06-19T11:47:11+02:00]                                               method=POST status=405 uri=/api/v1/dashboards
```

All steps worked but server said 405 Method Not Allowed.
