### ISSUE TITLE
Date range picker on Debian Linux 6.12.1 aarch64 gives error

### ISSUE THREAD

**Issue by pkkrusty** [perses/perses#3034]
### What did you do?

If I choose date range from 1970-01-01 00:00:00 to 1970-01-01 00:20:00, I get an error where 1200 is passed to the parser instead of 1970

<img width="1617" alt="Image" src="https://github.com/user-attachments/assets/22169522-b22f-4fa4-b0bd-0d5e533d5387" />

### What did you expect to see?

Date range accepted as valid

### What did you see instead? Under which circumstances?

Date range incorrectly flagged is invalid

### System information

Linux 6.12.1 aarch64

### Perses version

0.51.0 beta.1

### Perses configuration file

```yaml
{
  "security": {
    "readonly": false,
    "cookie": {
      "same_site": "lax",
      "secure": false
    },
    "encryption_key": "<secret>",
    "enable_auth": false,
    "authorization": {
      "check_latest_update_interval": "30s"
    },
    "authentication": {
      "access_token_ttl": "15m",
      "refresh_token_ttl": "1d",
      "disable_sign_up": false,
      "providers": {
        "enable_native": false
      }
    }
  },
  "database": {
    "file": {
      "folder": "./data",
      "extension": "json",
      "case_sensitive": false
    }
  },
  "dashboard": {},
  "provisioning": {
    "interval": "1h"
  },
  "datasource": {
    "global": {
      "disable": false
    },
    "project": {
      "disable": false
    },
    "disable_local": false
  },
  "variable": {
    "global": {
      "disable": false
    },
    "project": {
      "disable": false
    },
    "disable_local": false
  },
  "ephemeral_dashboard": {
    "enable": false,
    "cleanup_interval": "0s"
  },
  "frontend": {
    "disable": false,
    "explorer": {
      "enable": false
    },
    "time_range": {
      "disable_custom": false,
      "options": [
        "5m",
        "15m",
        "30m",
        "1h",
        "6h",
        "12h",
        "1d",
        "1w",
        "2w"
      ]
    }
  },
  "plugin": {
    "path": "plugins",
    "archive_path": "plugins-archive"
  }
}
```

### Logs

```text

```
