### ISSUE TITLE
Datasource discovery

### ISSUE THREAD

**Issue by Nexucis** [perses/perses#74]
Instead of providing the direct URL to the Prometheus server, it could be interesting use a discovery (and so to have the corresponding config).

We can start to support k8s discovery. Others can come later

**Comment by Nexucis** [comment]
This will modify the current `HTTPProxy` configuration by adding a new field `discovery`. It will also make the field `url` optional.

So the `HTTPProxy` definition is becoming:

```yaml
kind: "HTTPProxy"
spec:
  # URL is the url of datasource. It is not the url of the proxy.
  # Note: URL and discovery are mutually exclusive
  [ url: <url> ]

  # It is a tuple list of http methods and http endpoints that will be accessible.
  # Leave it empty if you don't want to restrict the access to the datasource.
  allowedEndpoints:
    - [ <Allowed Endpoints specification> ]

  # It can be used to provide additional headers that need to be forwarded when requesting the datasource
  headers:
    [ <string>: <string> ]
  # This is the name of the secret that should be used for the proxy or discovery configuration
  # It will contain any sensitive information such as password, token, certificate.
  # Please read the documentation about secrets to understand how to create one
  [ secret: <string> ]
  
  # This is the discovery configuration.
  [ discovery: <discovery_spec> ]
```

With the following `discovery_spec`:

```yaml
kind: "Kubernetes"
spec:
  # The namespace where the datasource is running
  namespace: <string>

  # The role Perses should use to contact the datasource
  role: <enum = "service" | "ingress">

  # The name of the service or of the ingress.
  name: <string>

  # The portName used when contacting the datasource
  # It's not necessary to define it
  [ portName: <string> ]
  [ portNumber: <number> ]
```

For the moment, I believe we don't need to support discovery by labels since we want to target a single service / ingress. So setting the name of the service will insure we are finding a single service and not multiple one, which is possible when finding service by labels.
